version: "3.9"
services:
    nextcloudsync:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        volumes:
          - ./data:/data
        restart: "on-failure"
